# for development purposes
version: '3.4'

services:
  pg:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    volumes:
      - 'static:/opt/{{ cookiecutter.repo_name }}/static:rw'
    depends_on:
      - pg

  nginx:
    image: nginx
    volumes:
      - './config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - 'static:/opt/{{ cookiecutter.repo_name }}/static:ro'
    depends_on:
      - web

volumes:
  pg-data:
  static:
